### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by Visionmaster70** [UPetersen/Unfalldatenatlas#1]
Hallo Herr Peterson,

gibt es eine Möglichkeit, mit ihnen direkt in kontakt zu kommen?
Ich hätte gern mit ihnen zu dem LibreMonitor gesprochen.

Vielen Dank
Ralph

**Comment by UPetersen** [comment]
Hallo Ralph,
ja, gerne. Was mir als einfacher Weg einfällt wäre z. B.  dass Du Deine E-Mail-Adresse (mit Leerzeichen und so) in den Issue schreibst und danach wieder löschst. Ich bekomme den Text immer auch per Mailnotiz an meine E-Mailadresse und kann mich dann melden. 
viele Grüße
Uwe

**Comment by Visionmaster70** [comment]
Kannst Du mir nicht einfach Deine Email-Adresse schreiben?
 
Von: UPetersen ***@***.*** 
Gesendet: Donnerstag, 20. Juli 2023 08:59
An: UPetersen/Unfalldatenatlas ***@***.***>
Cc: Visionmaster70 ***@***.***>; Author ***@***.***>
Betreff: Re: [UPetersen/Unfalldatenatlas] Kontakt (Issue #1)
 
Hallo Ralph,
ja, gerne. Was mir als einfacher Weg einfällt wäre z. B. dass Du Deine E-Mail-Adresse (mit Leerzeichen und so) in den Issue schreibst und danach wieder löschst. Ich bekomme den Text immer auch per Mailnotiz an meine E-Mailadresse und kann mich dann melden.
viele Grüße
Uwe

**Comment by Visionmaster70** [comment]
Du erreichst mich unter ralph.stelzer@arcor.de
